### PR TITLE
issue-59 sticky behavior and some footer style fixes

### LINKED ISSUE #59: Side content fragments gets sticky when scroll to middle of the page
Side content fragments gets sticky when scroll to middle of the page

See crn.com or any page to observe the behavior

Screenshot 2023-09-26 at 10 53 58 AM

### PR DESCRIPTION
**Pull request by samuelopra**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #59

Test URLs:
- Before: https://main--channelco-crn-com--hlxsites.hlx.page/
- After: https://issue-59--channelco-crn-com--hlxsites.hlx.page/

### CODE REVIEW

File: scripts/delayed.js [hunk 1]
```diff
@@ -106,6 +106,53 @@ function loadBottomAd() {
   }
 }
 
+function makeSticky() {
+  const adWrappers = document.querySelectorAll('.ad-wrapper');
+  const lastAd = adWrappers[adWrappers.length - 1];
+
+  const bannerWrappers = document.querySelectorAll('.banner-wrapper');
+  const lastBanner = bannerWrappers[bannerWrappers.length - 1];
```
Comment (kunwarsaluja) [inline scripts/delayed.js:114]: can't we do something like 

```
  const lastAd = document.querySelector('.ad-wrapper:last-of-type');
  const lastBanner = document.querySelector('.banner-wrapper:last-of-type');
```

File: scripts/delayed.js [hunk 2]
```diff
@@ -106,6 +106,53 @@ function loadBottomAd() {
...
+      // Reset the style when scrolling up, on mobile, or past the maxScrollPosition
+      lastAd.style.position = 'static';
+      lastAd.style.top = 'auto';
+      lastAd.style.width = 'auto';
+
+      lastBanner.style.position = 'static';
+      lastBanner.style.top = 'auto';
+      lastBanner.style.width = 'auto';
+    }
+  }
```
Comment (kunwarsaluja) [inline scripts/delayed.js:150]: would it make sense to toggle the classes instead of adding it all in the js plus adding some improvements around debouncing the scroll event so it isnt firing like crazy every second user scrolls the page, something like below

 ```
 function handleScroll() {
    clearTimeout(scrollTimeout);
    scrollTimeout = setTimeout(() => {
      const { scrollY } = window;
      const screenWidth = window.innerWidth;
      const shouldSticky = scrollY >= lastAdOffsetTop && screenWidth > mobileScreenWidthThreshold;

      lastAd.classList.toggle('sticky', shouldSticky);
      lastBanner.classList.toggle('sticky', shouldSticky);
    }, 50); 
  }
```

**Review by kunwarsaluja — CHANGES_REQUESTED** [review]

File: scripts/delayed.js (hunk 1 above)
Comment (samuelopra) [reply scripts/delayed.js:114]: no, this didnt work, which is the reason I opted for this

**Review by kunwarsaluja — APPROVED** [review]
